package me.asofold.bpl.rsp.core;

public enum RSPError {
	NULL_LOCATION,
	NULL_WORLD,
	NOT_PRESENT_PERMISSIONS,
	NOT_AVAILABLE_PERMISSIONS,
	ERROR_PERMISSIONS,
	NOT_PRESENT_REGIONS,
	FAILED_SCHEDULING_PARKED,
	SAVE_PERMISSIONS, 
	ADD_GROUP,
	REMOVE_GROUP,
}
